services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - default
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db
    pull_policy: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - default
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    pull_policy: always
  
  server:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - default
    pull_policy: build
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - default
    pull_policy: build

volumes:
  mongodb-data:
    driver: local

networks:
  default:
    name: finance-network
    driver: bridge
